CREATE TRIGGER [dbo].[InsteadOfInsertJobOrder] ON [dbo].[JobOrder] INSTEAD OF INSERT AS BEGIN 
SET 
  NOCOUNT ON INSERT INTO dbo.JobOrder (
    vendor_id, region_id, no, type, date, 
    mid, tid, officer_name, status, merchant_name, 
    address1, address2, address3, address4, 
    subdistrict, village, city, postal_code, 
    pic, phone_number1, phone_number2, 
    provider, trx_type_mini_atm, trx_type_visa, 
    trx_type_master, trx_type_jcb, trx_type_maestro, 
    trx_type_gpn, trx_type_tapcash_topup, 
    trx_type_tapcash_purchase, trx_type_qrcode_qris, 
    trx_type_qrcode_linkaja, trx_type_contactless_master, 
    trx_type_contractless_visa, edc_facility_cepp_plan1, 
    edc_facility_cepp_plan2, edc_facility_cepp_plan3, 
    edc_facility_reedem_point, edc_facility_activation_keyinsales, 
    edc_facility_activation_keyinsales_keyinpreauth_completion, 
    edc_facility_activation_keyinpreauth_completion, 
    edc_facility_activation_preauth_completion, 
    edc_facility_activation_keyinsales_preauth_completion, 
    edc_facility_offline, edc_facility_card_ver, 
    edc_facility_refund, edc_facility_adjust_tip, 
    trx_test_credit, trx_test_debit, 
    trx_test_inquiry, trx_test_transfer, 
    trx_test_jcb, trx_test_gpn, trx_test_tapcash, 
    trx_test_qris, trx_test_linkaja, 
    trx_test_visa_contactless, trx_test_master_contactless, 
    trx_test_instalment, trx_test_reedemption, 
    thermal_paper, sticker_bni, acrylic, 
    description1, description2, merchant_category, 
    ownership, created_by, updated_by, 
    created_at, updated_at, deleted_at
  ) 
SELECT 
  ins.vendor_id, 
  ins.region_id, 
  CONCAT(
    ins.no, 
    RIGHT(
      CONCAT(
        '00000', NEXT VALUE FOR JobOrderSeq
      ), 
      6
    )
  ) as no, 
  ins.type, 
  ins.date, 
  ins.mid, 
  ins.tid, 
  ins.officer_name, 
  ins.status, 
  ins.merchant_name, 
  ins.address1, 
  ins.address2, 
  ins.address3, 
  ins.address4, 
  ins.subdistrict, 
  ins.village, 
  ins.city, 
  ins.postal_code, 
  ins.pic, 
  ins.phone_number1, 
  ins.phone_number2, 
  ins.provider, 
  ins.trx_type_mini_atm, 
  ins.trx_type_visa, 
  ins.trx_type_master, 
  ins.trx_type_jcb, 
  ins.trx_type_maestro, 
  ins.trx_type_gpn, 
  ins.trx_type_tapcash_topup, 
  ins.trx_type_tapcash_purchase, 
  ins.trx_type_qrcode_qris, 
  ins.trx_type_qrcode_linkaja, 
  ins.trx_type_contactless_master, 
  ins.trx_type_contractless_visa, 
  ins.edc_facility_cepp_plan1, 
  ins.edc_facility_cepp_plan2, 
  ins.edc_facility_cepp_plan3, 
  ins.edc_facility_reedem_point, 
  ins.edc_facility_activation_keyinsales, 
  ins.edc_facility_activation_keyinsales_keyinpreauth_completion, 
  ins.edc_facility_activation_keyinpreauth_completion, 
  ins.edc_facility_activation_preauth_completion, 
  ins.edc_facility_activation_keyinsales_preauth_completion, 
  ins.edc_facility_offline, 
  ins.edc_facility_card_ver, 
  ins.edc_facility_refund, 
  ins.edc_facility_adjust_tip, 
  ins.trx_test_credit, 
  ins.trx_test_debit, 
  ins.trx_test_inquiry, 
  ins.trx_test_transfer, 
  ins.trx_test_jcb, 
  ins.trx_test_gpn, 
  ins.trx_test_tapcash, 
  ins.trx_test_qris, 
  ins.trx_test_linkaja, 
  ins.trx_test_visa_contactless, 
  ins.trx_test_master_contactless, 
  ins.trx_test_instalment, 
  ins.trx_test_reedemption, 
  ins.thermal_paper, 
  ins.sticker_bni, 
  ins.acrylic, 
  ins.description1, 
  ins.description2, 
  ins.merchant_category, 
  ins.ownership, 
  ins.created_by, 
  ins.updated_by, 
  ins.created_at, 
  ins.updated_at, 
  ins.deleted_at 
FROM 
  INSERTED AS ins 
SELECT 
  id 
FROM 
  dbo.JobOrder 
WHERE 
  @@ROWCOUNT > 0 
  AND id = scope_identity();
END
